### ISSUE TITLE
GitHub clone of the main repo

### ISSUE THREAD

**Issue by jgonggrijp** [vasile-gh/spamgourmet-clone#1]
Hi @vasile-gh,

Just letting you know that this exists since a few days: https://github.com/eegeeZA/spamgourmet-clone (not mine). You may want to mention it in the instructions and/or use it in the script.

Cheers.

CC @eegeeZA @shinyone @dragos-niculescu @nrbray

**Comment by mikedlr** [comment]
Have created https://github.com/vasile-gh/spamgourmet-clone/pull/2 which changes over to using the new repo.

**Comment by vasile-gh** [comment]
OK so I accepted the merge.

In any case I intend to rejig the script to make it work on Debian bullseye - I want to upgrade my instance to Debian 11 and might as well upgrade the script too.

Also, sorry but I am not well versed in github - what is the best way to get rid of this repo and let the fork take over? Does the fork depend on this repo? Can we "upgrade" the fork so it becomes main and then delete this repo?

Thoughts?

**Comment by eegeeZA** [comment]
If you maintain it separately, you will not need to worry about creating pull requests when you want to make changes on your script. We do cross link from the main Readme page to your site. But if you want to merge your script into main code, I think we can take that discussion up with @josiah-hamilton

**Comment by vasile-gh** [comment]
I like the idea of this script showing up under spamgourmet on github, but I also like the idea of me being able to change it as I wish - without a pull request.

Is there a way to have both things?

**Comment by vasile-gh** [comment]
So basically I would like to be able to change spamgourmet/spamgoumet-clone just like I change this repo.

If that is achievable, this particular repo would no longer be needed.

**Comment by eegeeZA** [comment]
It might work out if link we your current repo as a [submodule](https://github.blog/2016-02-01-working-with-submodules/). Then the only change would be to update the submodule's commit hash from time to time. Do you want to try that out?

**Comment by mikedlr** [comment]
I'm strongly against submodules except in very specific circumstances (basically vendoring) - they cause quite a bunch of problems because they check out a particular hash rather than a branch making the tracking difficult.  

Given that @vasile-gh  is part of the spamgourmet project, two options will give him full ability to deal with this

1) we keep it as a separate repo but move it into spamgourmet  
   a) rename current fork
   b) vasile moves the project
   c) spamgourmet project accepts and marks Vasile as an owner
   d) continue working in the new location as before

2) we merge the two repos - 
  a) I create a branch of each repo
  b) I move all spamgourmet-clone to a subdirectory
  c) I do a merge pulling the history of spamgourmet-clone into the main spamgourmet directory
  d) ensure that Vasile has full write access to repo
  e) Vasile is now editing in a subdirectory of the spamgourmet 
  f) Vasile, as a member of the project has his own branch - he edits that as he wishes 
  g) PRs done as needed either by Vasile or by anyone else that wants his code

I'm open to either but I strongly prefer 2) especially as I already began working on containerisation based around Vasile's code.  I think that it really belongs as a main part of the spamgourmet code.

**Comment by mikedlr** [comment]
BTW - in the above I assume that I do the work - no problem with anyone else having done it, but I've done exactly this thing a number of times which means I can do it easily and quickly which is good because it's a one off slightly fiddly thing.

**Comment by eegeeZA** [comment]
Cool, I'm also not too fond of submodules. I like the two options you proposed @mikedlr.

With option 2c, it's good that you'll keep the history. Because even though it might look odd with two starting commits, I much rather prefer having the history and changes included.

**Comment by vasile-gh** [comment]
Yes.

Let's keep it simple, and keep just one repo, the main spamgourmet one.

I am no programmer (as you undoubtedly realised as soon as you read my code) and I really did the script to scratch an itch I had. I am open to other people contributing to it and I'm thrilled by the idea that someone used it to also clone SG, and also that someone is using it to help containerise SG.

So **I am open to option 2 above - merge the two repos**.

Just let me know what do I need to do on my side - I would assume my "old" repo will die in the process, and I guess I will have to be the one doing the killing - RIP.
